import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Explicit sidebar: stable order, clear IA. Autogenerated categories stay in sync
 * with `docs/` when adding new pages.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Git Best Practices',
      link: {
        type: 'doc',
        id: 'git-best-practices/overview',
      },
      items: [
        'git-best-practices/overview',
        'git-best-practices/branching-strategy',
        'git-best-practices/conventional-commits',
        'git-best-practices/code-reviews',
        'git-best-practices/release-management',
        'git-best-practices/security',
        'git-best-practices/workflow-automation',
      ],
    },
    {
      type: 'doc',
      id: 'PROJECT_UPGRADE',
      label: 'Platform upgrade',
    },
  ],
};

export default sidebars;
